# Site settings
baseurl = "http://nodejh.com/"
languageCode = "zh-cn"
title = "nodejh"
theme = "hugo-theme-simple"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-84989670-1"

[params]
	name = "nodejh"
	description = "My Blog"
	bio = "To Be A Full Stack Developer"
	# Enter optionally your twitter account
	twitter = "nodejh"
	enableRSS = false

	# Disable comments by leaving disqusShortname empty
	disqusShortname = "nodejh"
	enableDisqus = false

	# Duoshuo Comment
	duoshuoShortname = "nodejh"
	enableDuoshuo = true

	enableGithubIssuesTips = false


	# Use description as title in single page, posts page and tags page.
	useDescriptionAsTitle = true

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I am so interesting."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = "circle"


# Add additional social link entries underneath
[social]
	facebook-square = "https://www.facebook.com/nodejh"
  twitter = "https://www.twitter.com/nodejh"
	stack-overflow = "http://stackoverflow.com/users/4518882/nodejh"
  github = "https://www.github.com/nodejh"
